### ISSUE TITLE
能否将这个 executor_detect_flag 变量作为 CallbackAwaiter 类的成员变量？

### ISSUE THREAD

**Issue by Jackarain** [avplayer/ucoro#32]
https://github.com/avplayer/ucoro/blob/a44f0fa6d68840332304840f5182d5863c7506d6/include/ucoro/awaitable.hpp#L557

我们是否能将这个 `executor_detect_flag` 变量作为 `CallbackAwaiter` 类的成员变量，如果可以，这样我们可以不使用 `shared_ptr`，如果不可以，请 @microcai 说明这样设计的理由，谢谢。

**Comment by microcai** [comment]
可以的。但是遇到了严重的问题。暂时解决不了。诶。

**Comment by Jackarain** [comment]
> 可以的。但是遇到了严重的问题。暂时解决不了。诶。

什么严重的问题，能否描述一下？

**Comment by microcai** [comment]
@Jackarain 就是不知道为何，跑着跑着，executor_detect_flag 的初始值就变成了 true

**Comment by Jackarain** [comment]
此问题已经解决：https://github.com/avplayer/ucoro/pull/36
