### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by zwkno1** [avplayer/ucoro#44]
https://github.com/avplayer/ucoro/blob/3e4d0445483a46ab07bd88ab98590f15ab515179/include/ucoro/awaitable.hpp#L361

else分支不是constexpr，static_assert会报错

编译器：
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.5.0

**Comment by microcai** [comment]
有没有详细的错误日志。你自己定位到的错误地方是你臆想出来的。

**Comment by zwkno1** [comment]
ucoro/include/ucoro/awaitable.hpp:361:5: error: static assertion failed: co_await must been used on an awaitable
                                static_assert(0, "co_await must been used on an awaitable");
                                ^             ~
1 error generated.
make[2]: *** [tests/test1/CMakeFiles/test1.dir/test1.cpp.o] Error 1
make[1]: *** [tests/test1/CMakeFiles/test1.dir/all] Error 2

**Comment by microcai** [comment]
你还是截断了，就不能发完整的吗？

**Comment by zwkno1** [comment]
<img width="1275" alt="image" src="https://github.com/user-attachments/assets/c0a750d5-96d2-4058-9360-2a263243c68e">

**Comment by microcai** [comment]
至少需要编译器提供错误的时候， 是被哪行代码调用导致 static_assert 的，调用的时候，编译器推导的模板参数是啥。
如果编译器不能提供这些，那这个编译器根本无助于调试代码。只能说不是一个合格的编译器。

**Comment by microcai** [comment]
大概率是因为你的编译器太老了，不支持 c++20

**Comment by zwkno1** [comment]
第二行include就报错了

**Comment by microcai** [comment]
看来你使用 c++ 的时间太短了。不知道水果的编译器就是垃圾。他的 appleClang  的版本号并不跟上游。 appleclang 15 大约相当于上游的 clang-5.5

**Comment by microcai** [comment]
确定是编译器 bug. 只能绕过了。
